### ISSUE TITLE
Crashes On Start Up

### ISSUE THREAD

**Issue by toErIpNid** [Alastors/thaumicinsurgence#26]
Crashlog: https://hastebin.skyra.pw/fixudasete.yaml

Using latest forge version for 1.7.10 and 0.2.4 of insurgence.

**Comment by Alastors** [comment]
> Crashlog: https://hastebin.skyra.pw/fixudasete.yaml
> 
> 
> 
> Using latest forge version for 1.7.10 and 0.2.4 of insurgence.

https://github.com/GTNewHorizons/thaumicinsurgence/releases would you mind trying this version and seeing if it does the same?

**Comment by Alastors** [comment]
This appears to be a custom modpack, if this issue persists in this latest release, I'll quickly push another version disabling the code for the pact ring for the time being

**Comment by Alastors** [comment]
It's really strange though, I've never seen this crash happen before in general, I wonder if it may be compat issues with one of your other mods

**Comment by toErIpNid** [comment]
Probably, I'm using a mix of modrinth and curseforge mods and several are relatively new releases. Using this latest GTNH version you sent me fixed the issue and everything work. 

While I'm here, I'm a little concerned about the balance of the mod as it doesn't really state what anything does, what do the various items do beyond the madman's lense?

**Comment by Alastors** [comment]
> Probably, I'm using a mix of modrinth and curseforge mods and several are relatively new releases. Using this latest GTNH version you sent me fixed the issue and everything works. 
> 
> 
> 
> While I'm here, I'm a little concerned about the balance of the mod as it doesn't really state what anything does, what do the various items do beyond the madman's lense? 

First of that's super strange lmfaooooo, I wonder what broke between the two.

And the balance of the mod:

Okay so first off you have those goggles that I made, they're mostly just a joke back when I was going through a spamton craze, just 8% discount for 5 warping pretty basic.

The soaps: 
the Trosma soap is a buffed warp removal soap that makes the max removal go up to 100% (including the buffs so at base it's up from 33% of the original to 50%)

The Alastor's soap has a base 10% chance max 40% chance to transmute 1 perm warp into 2 normal warp and produces 2 temp warp on failure.

Regarding the soaps, they are a little underpowered for the time being, im still working out their exact golden spot but I work for a expert level pack (GTNH) so I initially tiered them a little extreme so they'd get in relatively easily and am dealing with the issues now.

Regarding the pact ring: doesn't exist yet, it's currently a planned cursed item that unlocks the power of various planned items and planned routes of specific things such as the goggles.

Regarding the madman's lens: it's a dev tool, though it does calculate approximate cVis rates of nodes if you energized them so I let players use it as well.

Regarding the intercepter: it's severely underpowered without Thaumic Energistics, but effectively you use the bottom face to pipe in essentia, and instead of using the infusion provider from ThE, you can place the essentia provider (or essentia pipes I guess for a speed penalty) and it'll handle all essentia of an infusion in O(1) or 1 tick and gets rid of the lag related to that such as the particle effects and whatnot.

Regarding Altar Alpha: it's a planned altar upgrade that'll handle sucking in every item in 1 tick.

Regarding the mod as a whole: this mod is not a GTNH mod though I do develop it with GTNH in mind since I work for them. Most of my development cycle is documented on their discord if you would like me to provide you a link, I also work on other mods for them, for example, I have recently effectively become the successor dev to Thaumic Horizons by it's original dev.

I hope I have answered all of your questions? Do you have any more questions or concerns?

**Comment by toErIpNid** [comment]
"I have recently effectively become the successor dev to Thaumic Horizons by it's original dev."

Wait, really? Is it on a new mod page or the old one? I just downloaded that! Also yeah that's what I was looking for.

**Comment by Alastors** [comment]
> "I have recently effectively become the successor dev to Thaumic Horizons by it's original dev."
> 
> 
> 
> Wait, really? Is it on a new mod page or the old one? I just downloaded that! Also yeah that's what I was looking for. 

It's on the original page actually, one of our team's legal guys is technically the "owner" of the curseforge page due to some legal mumbo jumbo that's way over my head, but I'm now the primary maintainer of the mod, and Kentington has provided me all of his notes from when he was originally working on the mod with unfinished ideas and etc, so one of the things I'm working on is implementing as much of his desired unfinished content as I possibly can.

The next update to the mod should include around 7 new nether/planar primal aspects in ties with his first request! 

It's insane though, thaumic horizons was the reason I started deving in the first place and now I'm listed as one of its maintainers on curseforge, life is wild mate

**Comment by Alastors** [comment]
I will note, I am planning on releasing the next version on Modrinth as well assuming Mitch hasn't gotten to it before me 😂

**Comment by toErIpNid** [comment]
Sweet! By the way, I'm still using Unidict to unify stuff, do you know if there's a better mod out there I should be using instead? It seems 1.7 has had a burst of new life recently.

**Comment by Alastors** [comment]
> Sweet! By the way, I'm still using Unidict to unify stuff, do you know if there's a better mod out there I should be using instead? It seems 1.7 has had a burst of new life recently. 

I don't know off the top of my head, but maybe try #Mod-Dev on the GTNH server? They would probably know more on the topic than I would 😅 https://discord.gg/gtnh

And yeah! It's really crazy, I think it might be directly or indirectly because of the GTNH modpack and the sheer amount of QoL updates and support we've continued to provide, and have recently ramped up on tbh! 

It was absolutely insane seeing our variant of NEI get brought into Technic's Blightfall

**Comment by toErIpNid** [comment]
Anyways thanks for everything dude! Excited to see what you do for horizons!
